### ISSUE TITLE
Global ray didn't load in MAMP environment

### ISSUE THREAD

**Issue by aaronmeder** [spatie/global-ray#14]
Hey there

first of all: thanks a ton for providing Ray and this package which makes debugging easy breezy! 🙌🏻

### Problem encountered ### 

The ray command (and dd) would not load as expected in my environment causing a "Call to undefined function ray()" error.

### Environment ### 

macOS Monterey (pretty fresh install), MAMP Pro, PHP 8.0.8, Wordpress PHP website

I have MAMP configured to publish it's PHP version to the command line:
<img width="659" alt="Screenshot 2022-03-08 at 16 55 16" src="https://user-images.githubusercontent.com/5564163/157274900-50060f7f-86c6-450c-af79-75125b2594c1.png">

### Source of problem ### 

It seems like ray added itself to the wrong PHP ini file:

```
🤙 Do you wish to install Ray globally? (Y/n) > Y
Updating PHP ini: /Applications/MAMP/bin/php/php8.0.8/conf/php.ini...
```
   
If I check which php.ini is used on my command line:
```
➜  ~ php -i | grep "Configuration File"
Configuration File (php.ini) Path => /Applications/MAMP/bin/php/php8.0.8/conf
Loaded Configuration File => /Library/Application Support/appsolute/MAMP PRO/conf/php8.0.8.ini
```

### Solution to problem ### 
I've copied the followingline that Global ray added also to the "/Library/Application Support/appsolute/MAMP PRO/conf/php8.0.8.ini" file:

`auto_prepend_file = /Users/aaron/.composer/vendor/spatie/global-ray/src/scripts/global-ray-loader.php`

After that it works like a charm.

Please reply if I can provide any other information.

Aaron

**Comment by stevebauman** [comment]
Hi @aaronmeder! Thanks for the detailed issue. I think we can offer a choice with different PHP ini files that have been found on the system during installation. For example:

```
🤙 Do you wish to install Ray globally? (Y/n) > Y

Choose a PHP ini file to install to:

- /Applications/MAMP/bin/php/php8.0.8/conf.ini
- /Library/Application Support/appsolute/MAMP PRO/conf/php8.0.8.ini <-
``` 

Let me see what I can put together 👍

**Comment by aaronmeder** [comment]
>  I think we can offer a choice with different PHP ini files that have been found on the system during installation. 

Thanks sounds great to me! 
Maybe even add an "Add to all" option? Since global-ray seems to be about making it run everywhere that would be a helpful step to make sure it does run everywhere ;-)

**Comment by stevebauman** [comment]
That's a great idea @aaronmeder! Didn't think of that -- I'll definitely add that in 👍
