### ISSUE TITLE
Global Ray doesn't work with artisan serve

### ISSUE THREAD

**Issue by driesvints** [spatie/global-ray#17]
For some bizar reason, Global Ray has stopped working for me. Everytime I try to use `ray`, `dd` or `dump` nothing happens for me and nothing appears in Ray. I have no idea how this happened or where to begin to troubleshoot...

I've tried:

- Restarting and reinstalling Ray
- Restarting PHP 8.1 & 8.0
- Checked if the `auto_prepend_file` config is correct in php.ini
- Restarting and upgrading PHP Monitor

Any help is greatly appreciated.

**Comment by freekmurze** [comment]
Things you can try:

- run `php --ini` and check if the ini file being loaded is the one where the `auto_prepend_file` is modified
- try to replace our script at `auto_prepend_file` by a script of your own that does something simple you can verify (maybe an `echo` or something like that)
- maybe you're using a different PHP binary for CLI and web request, and this is what confuses you? Create a script with `phpinfo()`, let in render in the browser and check the path to the ini file there.

**Comment by driesvints** [comment]
Thanks!

1. Yes that's the case
2. I can see the echo in CLI but now when running the app on a web request
3. From testing 2. I also thought this but it seems it's definitely the same file (see the screenshots below)

<img width="1018" alt="Screenshot 2022-03-22 at 10 56 31" src="https://user-images.githubusercontent.com/594614/159454905-05770e9d-3952-4058-b2f0-dc4e17cf1dae.png">
<img width="879" alt="Screenshot 2022-03-22 at 10 56 26" src="https://user-images.githubusercontent.com/594614/159454911-950828d2-a29b-4758-80ae-2343df02dae7.png">

**Comment by freekmurze** [comment]
If you create a new project and install Ray into it, does it work?

I'm afraid of suggestion this 

![have-you-tried-rebooting-it-yet](https://user-images.githubusercontent.com/483853/159465727-d036ed61-add6-49d6-80f2-fb703e753cc9.jpg)
but...

**Comment by driesvints** [comment]
> If you create a new project and install Ray into it, does it work?

I'll try that in a sec.

I'm currently trying:

```
Route::get('/', function () {
    dd(ini_get('auto_prepend_file'));

    ray('test');

    return view('welcome');
});
```

The `dd` gives me `/Users/driesvints/.composer/vendor/spatie/global-ray/src/scripts/global-ray-loader.php` so the correct prepend is loaded. But when I remove it I get the Ignition error screen saying `ray` cannot be found.

> I'm afraid of suggestion this but...

Yeah, just tried that, no luck :/

I also tried reinstalling Valet and upgrading PHP monitor. Both didn't work. I'm at a complete loss here 😓

**Comment by driesvints** [comment]
Can confirm that `spatie/laravel-ray` works when installed. Global Ray doesn't.

**Comment by driesvints** [comment]
If I access `phpinfo()` from PHP Monitor I see `file:///private/tmp/phpmon_phpinfo.html` as the url and I can see the echo statement from within the ray loader file: `/Users/driesvints/.composer/vendor/spatie/global-ray/src/scripts/global-ray-loader.php`.

But if I do `return phpinfo();` as the very first line of `public/index.php` in a Laravel app I see the php info without the echo statement. Maybe this is a Valet thing?

**Comment by driesvints** [comment]
Beginning to strongly suspect this is a Valet thing. I tried running `php -S localhost:8888` and then I start seeing the echo statement and the `ray` function starts working if I use it in `public/index.php`.

**Comment by stevebauman** [comment]
Hey @driesvints!

global-ray will backoff from loading if it sees `ray` or `laravel-ray` as a composer dependency (via the `composer.json` file) in the current working directory: https://github.com/spatie/global-ray/blob/e10071c6385eb1909fe48b04dc2cd61bc0d31dcc/src/scripts/global-ray-loader.php#L50-L56

Could this be what you're experiencing?

**Comment by driesvints** [comment]
Hey @stevebauman. Thanks for helping out. I don't have spatie/laravel-ray installed and I'm not using PHP isolation.

**Comment by stevebauman** [comment]
Ok, can you try re-`use`'ing PHP 8.1 or 8.0 with Valet via `valet use php@8.1 --force`? I just tested with PHP 8.1 on my machine and it's working fine.

**Comment by driesvints** [comment]
```
$ valet use php@8.1 --force                                                                                                                                                                                ~/Sites/test-laravel
testUnlinking current version: php
Linking new version: php@8.1
Stopping php...
Updating PHP configuration...
Restarting php...
Restarting nginx...
Valet is now using php@8.1.

Note that you might need to run composer global update if your PHP version change affects the dependencies of global packages required by Composer.
```

And I still get the `Call to undefined function ray()`.

**Comment by driesvints** [comment]
@stevebauman I'm a bit closer. I was using `artisan serve` and mistakenly thought Valet was the culprit. When I use `valet link` and visit the site using the Valet link then it works for me. `php artisan serve` seems to not work.

**Comment by driesvints** [comment]
@stevebauman can you try artisan serve and the following route file?

```php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    ray('test');

    return view('welcome');
});
```

**Comment by stevebauman** [comment]
> `php artisan serve` seems to not work.

Yup you're right I'm able to reproduce this on my end 👍

**Comment by driesvints** [comment]
Sorry for the misdirection here. I should have noticed earlier that it's purely an artisan serve issue.

**Comment by stevebauman** [comment]
Hey @driesvints! This appears to be an issue with supplying a [router script](https://www.php.net/manual/en/features.commandline.webserver.php#example-468) in the [ServeCommand](https://github.com/laravel/framework/blob/2fec0a345d5960c8d546cc21ec8291126962c939/src/Illuminate/Foundation/Console/ServeCommand.php#L146).

Can you try opening up:

```
vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php
```

And then modifying this:

**From**:

```php
protected function serverCommand()
{
    $server = file_exists(base_path('server.php'))
        ? base_path('server.php')
        : __DIR__.'/../resources/server.php';

    return [
        (new PhpExecutableFinder)->find(false),
        '-S',
        $this->host().':'.$this->port(),
        $server,
    ];
}
```

**To**:

```php
protected function serverCommand()
{
    return [
        'php',
        '-S',
        $this->host().':'.$this->port(),
        '-t',
        public_path(),
    ];
}
```

You should see ray working. I believe the router script is altering the way the ini is loaded?

**Comment by driesvints** [comment]
@stevebauman that indeed worked! I'm not sure we can adjust that though... We also use artisan serve for Sail, etc.

Here's the server.php file but I can't see anything odd in it: https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/resources/server.php

**Comment by stevebauman** [comment]
@driesvints Do you think we could use `Foundation/resources/` as the root via the `-t` option and rename `server.php` to `index.php` to retain the `mod_rewrite` functionality?

**Comment by stevebauman** [comment]
Ah and here we go -- `auto_prepend_file` and `auto_append_file` are not used when specifying a router script:

https://bugs.php.net/bug.php?id=64566

https://github.com/jpauli/php-src/commit/eb44bd892679b350243123b76a8edcf0f84e31b8

**Comment by driesvints** [comment]
Heya sorry, I missed this a bit while being sick last week.

> Do you think we could use Foundation/resources/ as the root via the -t option and rename server.php to index.php to retain the mod_rewrite functionality?

I'm unsure. We could maybe duplicate it into a different directory but I'd need to check with the team. I'll check.

> Wonder if this is the same when specifying a "router" file:
> Ah and here we go -- auto_prepend_file and auto_append_file are not used when specifying a router script:

So I guess we can't go that way.

**Comment by driesvints** [comment]
> Do you think we could use Foundation/resources/ as the root via the -t option and rename server.php to index.php to retain the mod_rewrite functionality?

I tried that but it doesn't work. Getting a white page. I don't think we can simple rename the file? The directory probably needs to be the public dir of the app still? That would defeat the purpose of a `server.php` file.

**Comment by stevebauman** [comment]
Apologies for the late reply. 

> I tried that but it doesn't work. Getting a white page. I don't think we can simple rename the file? The directory probably needs to be the public dir of the app still?

Yea you're right -- I'm not sure of the path forward. Do you know if there a particular reason that Laravel doesn't use the `public` dir of the application to serve? Is it possibly for the `mod_rewrite` emulation?

**Comment by driesvints** [comment]
I have no idea myself... I'd have to ask my colleagues but afraid atm it's a bit too busy for that. I'll try to ask soon.
