### ISSUE TITLE
Anyone managed to get this working on linux based systems?

### ISSUE THREAD

**Issue by sunscreem** [spatie/global-ray#2]
Love the idea of not needing to install the package on a per-project basis. Trying to install on ubuntu 18 - php 8.0:

The package installs no problem but the global-ray is have permissions issues.

```bash
$ global-ray install
Updating PHP ini: /etc/php/8.0/cli/php.ini
PHP Warning:  file_put_contents(/etc/php/8.0/cli/php.ini): Failed to open stream: Permission denied in /home/forge/.composer/vendor/spatie/global-ray/src/Support/PhpIni.php on line 36

Warning: file_put_contents(/etc/php/8.0/cli/php.ini): Failed to open stream: Permission denied in /home/forge/.composer/vendor/spatie/global-ray/src/Support/PhpIni.php on line 36
Unable to update PHP ini.
```

Trying with `sudo` doesn't help.

```bash
$ sudo global-ray install
sudo: global-ray: command not found
```

**Comment by freekmurze** [comment]
This package has not been released yet. Please try a little bit later.

**Comment by sunscreem** [comment]
Thanks Freek!

**Comment by xewl** [comment]
Had the same problem now too inside WSL. My user has no write access to php.ini files.
Might be useful to skip the step on failure and tell us what to change instead of failing =D

**Comment by freekmurze** [comment]
>  My user has no write access to php.ini files.

Is there some kind of `sudo` in WSL that you can use?

**Comment by xewl** [comment]
> Is there some kind of `sudo` in WSL that you can use?

sure; sudo's def there.
It could indeed retry the PHP.ini replacement with sudo if it failed at first.
