### ISSUE TITLE
MacOS: global-ray not found

### ISSUE THREAD

**Issue by ArselMuginov** [spatie/global-ray#21]
Hello!

I wanted to install ray globally but zsh didn't find the global-ray executable. Composer require executed without errors. I have several PHP versions installed with brew, I don't know if it matters, the linked version is 7.4. if I specify the full path to the global-ray executable, it runs without a hitch. If I knew how to fix this bug I would've done it :)

Thank you for your time!

**Comment by ArselMuginov** [comment]
Also, after I installed global-ray, dump() throws an error saying that str_starts_with() is undefined (in dump_7.4.phar). Should I make a separate issue for this?

**Comment by VSG24** [comment]
I'm having the same issue with PHP 8.0. `zsh: command not found: global-ray`

**Comment by VSG24** [comment]
For future readers I had to run `composer global config --list` to get the path to global composer packages which in my case was `/Users/myusername/.composer/vendor/bin` and then execute `./global-ray install`
