### ISSUE TITLE
Method doesn't exist

### ISSUE THREAD

**Issue by yoeriboven** [spatie/global-ray#25]
I'm getting this error when using `ray()->showQueries()` in a test (so on CLI).

```bash
BadMethodCallException : Method showQueries does not exist.
 phar:///Users/username/.composer/vendor/spatie/global-ray/ray-phars/ray_php_8.1.phar/vendor/spatie/macroable/src/Macroable.php:42
```

Once I install ray locally in the project everything works.

**Comment by stevebauman** [comment]
Hi @yoeriboven,

Laravel-Ray has to be installed locally for `ray()->showQueries()` to work. The core Ray package does not have this method, which is installed via `global-ray`.
