### ISSUE TITLE
Global Ray doesn't work with artisan serve

### ISSUE THREAD

**Issue by driesvints** [spatie/global-ray#26]
> Re-opening https://github.com/spatie/global-ray/issues/17 because this still is happening it seems

For some bizar reason, Global Ray has stopped working for me. Every time I try to use `ray`, `dd` or `dump` nothing happens for me and nothing appears in Ray. I have no idea how this happened or where to begin to troubleshoot...

I've tried:

- Restarting and reinstalling Ray
- Restarting PHP 8.1 & 8.0
- Checked if the `auto_prepend_file` config is correct in php.ini
- Restarting and upgrading PHP Monitor

Any help is greatly appreciated.

**Comment by torbentschechne** [comment]
I use `valet link` for a non-laravel installation. And even though the correct php.ini is loaded and the `auto_prepend_file` is existent `ray` or `dd` do not work for me.

**Comment by stevebauman** [comment]
@torbentschechne Please see https://github.com/spatie/global-ray/issues/17 for the cause. This unfortunately cannot be resolved easily. Resolution requires Laravel to update it's mechanism of serving sites locally -- unless we can figure out a way for global-ray to run on all scripts with some other mechanism.

I've re-opened the previous issue for tracking and will continue to re-open if the bot takes it down 👍
