### ISSUE TITLE
Symfony Dumper calling str_contains in php 7.4 phar

### ISSUE THREAD

**Issue by filipac** [spatie/global-ray#36]
Hello,

I was debugging an older app and installed Global Ray to ease it. Apparently, there is a line in the PHAR for 7.4 that belongs to Symfony's VarDumper:

```
Uncaught Error: Call to undefined function str_contains() in phar:///Users/filipac/.composer/vendor/spatie/global-ray/ray-phars/ray_php_7.4.phar/vendor/symfony/var-dumper/Dumper/CliDumper.php:126
```

`str_contains` is only available in PHP 8.0+.

I am not sure this is the right repository to report it, it might belong to ray repo itself. I've been trying to fix it but I am not sure yet how to build the PHAR.

Later edit: I saw that a polyfill is used and the function should be available. This is weird.

**Comment by filipac** [comment]
Further investigation: The php 8.0 polyfill is there but the package is prefixed with a GlobalRay vendor so the functions are not polyfill in the global namespace.

**Comment by stevebauman** [comment]
Hi @filipac,

How is ray being called? Is it through an HTTP request on your local web server, using a terminal, through tinker/tinkerwell etc? Also, do you have other PHP versions installed on your computer?

I ask because I’m curious if the file in which you’ve placed the ray call may be executed by a different PHP version than anticipated, depending on how your system is setup.

**Comment by b0rt** [comment]
can confirm. using dockerfile php7.4-fpm

```dockerfild
FROM php:8.0-fpm
# skipped for brevity
# Install composer and add its bin to the PATH.
RUN curl -s http://getcomposer.org/installer | php && \
    echo "export PATH=${PATH}:/var/www/vendor/bin" >> ~/.bashrc && \
    mv composer.phar /usr/local/bin/composer
 RUN  composer global require spatie/global-ray
RUN /home/$USER/.composer/vendor/spatie/global-ray/bin/global-ray install --ini=/usr/local/etc/php/php.ini -n

```

**Comment by stevebauman** [comment]
Imo I don't think this is worth resolving at this point (feel free to PR of course if you find a resolution!), as PHP 7.4 is [well out of support](https://www.php.net/supported-versions.php). Will leave this closed for now.
