### ISSUE TITLE
Errors at top of PHP output on Herd / PHP 8.2

### ISSUE THREAD

**Issue by MikePriceAero** [spatie/global-ray#44]
I'm using Laravel Herd locally with `spatie/global-ray` installed via `composer global require` and it was working fine - until this morning.

When I open any page on my PHP 8.2 test sites at the moment, I'm getting these errors output at the top of the page:

```
Warning: file_get_contents(/Users/mike/.config/valet/config.json): Failed to open stream: No such file or directory in /Users/mike/.composer/vendor/spatie/global-ray/src/scripts/global-ray-loader.php on line 45

Warning: Attempt to read property "paths" on null in /Users/mike/.composer/vendor/spatie/global-ray/src/scripts/global-ray-loader.php on line 47

Warning: foreach() argument must be of type array|object, null given in /Users/mike/.composer/vendor/spatie/global-ray/src/scripts/global-ray-loader.php on line 47

Warning: file_get_contents(/Users/mike/.config/valet/config.json): Failed to open stream: No such file or directory in /Users/mike/.composer/vendor/spatie/global-ray/src/scripts/global-ray-loader.php on line 45

Warning: Attempt to read property "paths" on null in /Users/mike/.composer/vendor/spatie/global-ray/src/scripts/global-ray-loader.php on line 47

Warning: foreach() argument must be of type array|object, null given in /Users/mike/.composer/vendor/spatie/global-ray/src/scripts/global-ray-loader.php on line 47
```

...which then messes with the styling and output of the HTML page beneath it, or any other outputs that are generated via Laravel routes such as resized images etc.

I've tried a `composer global reinstall` and `global-ray install` again, but no luck.

I've been having some trouble with the clock on my MacBook resetting itself so I'm not sure if that's somehow related to these files apparently disappearing?

**Comment by joshuablum** [comment]
Same for me, can replicate. Started this morning for me and was just starting to look for a fix, and issues here were my first stop. Will report if I find a fix/workaround.

**Comment by joshuablum** [comment]
Opened in issue for this on the Herd support repo since I think it's related to Herd, not `global-ray` https://github.com/beyondcode/herd-community/issues/239.
