### ISSUE TITLE
Ray not working with PHP 8.3

### ISSUE THREAD

**Issue by mambax7** [spatie/global-ray#45]
On my Windows 10, I use WampServer and Laragon, and on both Ray works fine with **PHP 8.2**
When I switch to **PHP 8.3**, with the php.ini identical, I'm getting error:
```Error: Error: Call to undefined function ray() in file xxx.php line xxx```

**Comment by mambax7** [comment]
OK, I see the problem: you didn't provide: 
**```ray_php_8.3.phar```**
in https://github.com/spatie/global-ray/tree/main/ray-phars :(

But that's what the global-ray is looking for:
```php
class Ray
{
    public static function getPharPath()
    {
        $phpVersion = PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION;

        return __DIR__ . "/../../ray-phars/ray_php_{$phpVersion}.phar";
    }
}
```

When are you going to update it?

**Comment by freekmurze** [comment]
We now support PHP 8.3
