### ISSUE TITLE
Vanilla PHP missing LaravelRay\Ray

### ISSUE THREAD

**Issue by szhorvath** [spatie/global-ray#53]
Hi, 

I am having an issue where I would like to use Ray on a legacy project with plain PHP. No framework is present. I've added Composer for certain parts of the app but mainly just old-fashioned PHP files.

macOS: Sonoma 14.5
PHP 8.3.8
using built-in php server (php -S localhost:8888)

Global ray is installed successfully.
I can see the auto prepend is added
![image](https://github.com/spatie/global-ray/assets/38496732/fef02753-f79b-4da6-af97-d4b34535f84f)

When I attempt to use the Ray helper, it displays the following error message:

`Class GlobalRay\Spatie\LaravelRay\Ray not found`

I don't know what I am doing wrong, and I don't understand why it would want to look for LaravelRay.

**Comment by stevebauman** [comment]
Hi @szhorvath,

Does this issue still occur when you use a different web server vs the built-in one?

**Comment by szhorvath** [comment]
Hi @stevebauman,

Interestingly, I've just tried it in a docker container and added the `spatie/ray` package to the project to eliminate the nature of the global stuff. I am receiving the same `Class Spatie\LaravelRay\Ray not found` error but not a global namespace.

Here is my `composer.json`:

```json
{
    "require": {
        "php": "^8.2",
        "ext-curl": "*",
        "vlucas/phpdotenv": "^5.6",
        "illuminate/collections": "^11.11",
        "spatie/ray": "^1.41"
    },
    "require-dev": {
        "symfony/var-dumper": "^6.4.8",
        "friendsofphp/php-cs-fixer": "^3.59.3"
    },
    "autoload": {
        "files": [
            "app/helpers.php"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "scripts": {
        "fix-style": "vendor/bin/php-cs-fixer fix --allow-risky=yes",
        "check-style": "vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run"
    }
}
```

Many thanks for the help.
